name: test1_github_actions
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm init -y
      - run: npm install cypress --save-dev
      - run: npm -v
      - run: npx cypress run
