name: 🚀 GitHub Actions Demo (назва яку я бачу)
# Назва цього GitHub Actions, який проводить демонстрацію

run-name: 🚀(${{ github.actor }} тестує дії GitHub методом пуш) ${{ github.actor }} is testing out GitHub Actions
# Ім'я користувача GitHub, який виконує тестування GitHub Actions

on: [push]
# Виконувати цей шаблон при події "push" (завантаження) до репозиторію

jobs:
  # Об'єднує всі завдання, що виконуються у робочому процесі
  Explore-GitHub-Actions:
    # Задання для виконання в контексті GitHub Actions з назвою "Explore-GitHub-Actions"

    runs-on: ubuntu-latest
    # Виконувати це завдання на сервері з останньою версією Ubuntu

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event.(Це завдання було виконано автоматично при події ${{ github.event_name }})"
        # Виконати команду "echo" для виведення повідомлення, яке показує, що задача була автоматично спровокована подією з іменем ${{ github.event_name }}

      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        # Виконати команду "echo" для виведення повідомлення, яке показує, що задача зараз виконується на сервері ${{ runner.os }}, який надає GitHub

      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        # Виконати команду "echo" для виведення повідомлення, яке показує, що назва гілки - ${{ github.ref }}, а репозиторій - ${{ github.repository }}

      - name: Check out repository code
        uses: actions/checkout@v3
        # Використовувати дію "checkout" для клонування коду репозиторію

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
        # Виконати команду "echo" для виведення повідомлення, яке показує, що репозиторій ${{ github.repository }} був клонований на сервер

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
        # Виконати команду "echo" для виведення повідомлення, що показує, що робочий процес готовий для тестування вашого коду на сервері

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
        # Вивести список файлів у репозиторії

      - run: echo "🍏 This job's status is ${{ job.status }}."
        # Вивести статус завдання
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout (Тут додаю свої налаштування, поки щось не виходить)
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          # build: npm run build
          start: npm start
      - name: Create videos directory
        run: mkdir -p cypress/videos
        # Створюємо папку для збереження відео (на випадок якщо її не існує)
      - name: Save Cypress videos on failure
        if: ${{ failure() }}
        run: |
          mkdir -p videos
          mv cypress/videos/*.mp4 videos/
        # Команда для збереження відео з помилками у вказану папку
