name: Тобто мій перший тест сайпреса та гіт хаба   Cypress Tests (Cypress GitHub Action)

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly (Встановіть залежності NPM, кешуйте їх правильно)
      # and run all Cypress tests (і запустити всі тести Cypress)
      - name: Cypress run
        uses: cypress-io/github-action@v5

        # with:
        # build: npm run build
        # start: npm start
      - name: Запуск тестів Cypress (Run Cypress tests)
        run: npx cypress run --spec "cypress/e2e/modul_4_hw.cy.js"
